// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpRkCouqBeG0DJDPtu0R96VfKHfRqj9I',
    appId: '1:1064868524856:web:a91784194b2fa58c2647cd',
    messagingSenderId: '1064868524856',
    projectId: 'trochoi-95b1c',
    authDomain: 'trochoi-95b1c.firebaseapp.com',
    storageBucket: 'trochoi-95b1c.firebasestorage.app',
    measurementId: 'G-82P3DV3L15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXsNPSDxRGtQompIiPsSF3wbnMy6gC9E',
    appId: '1:1064868524856:android:35b2d3b8bc7f808d2647cd',
    messagingSenderId: '1064868524856',
    projectId: 'trochoi-95b1c',
    storageBucket: 'trochoi-95b1c.firebasestorage.app',
  );
}
